"""rename department

Revision ID: af043d8275ff
Revises: 47da7d7b9da8
Create Date: 2024-05-13 16:33:27.444604

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af043d8275ff"
down_revision = "47da7d7b9da8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("address", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id")
    op.drop_table("department")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
    sa.Column("id", sa.INTEGER(), nullable=False),
    sa.Column("name", sa.VARCHAR(), nullable=False),
    sa.Column("address", sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint("id")
    op.drop_table("departments")
    # ### end Alembic commands ###
